serviceName: servicename
imageURL: gcr.io/google-samples/microservices-demo/checkoutservice
imageTag: v0.5.2
replicaCount: 1
containerPort: 8080
containerEnvVars:
- name: ENV_VAR_ONE
  value: "valueone"
- name: ENV_VAR_TWO
  value: "valuetwo"

serviceType: ClusterIP
servicePort: 8080