architecture: replication
auth:
  rootPassword: secret-root-pw
  database: my-app-db
  username: my-user
  password: my-pass

# enable init container that changes the owner and group of the persistent volume mountpoint to runAsUser:fsGroup
volumePermissions:
  enabled: true

secondary:
  replicaCount: 2
  persistence:
    storageClass: linode-block-storage
    accessModes: ["ReadWriteOnce"]
