apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-mysql
  labels:
    app: java-mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-mysql
  template:
    metadata:
      labels:
        app: java-mysql
    spec:
      containers:
      - name: java-mysql
        image: jimsemara/java-mysql:1.0
        ports: 
        - containerPort: 8080
        env:
          - name: DB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mysql-configmap
                key: db_server
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: db_name
          - name: DB_USER
            valueFrom: 
              secretKeyRef:
                name: mysql-secret
                key: db_user
          - name: DB_PWD
            valueFrom: 
              secretKeyRef:
                name: mysql-secret
                key: db_password

---

apiVersion: v1
kind: Service
metadata:
  name: java-mysql-service
spec:
  selector:
    app: java-mysql-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080